### ISSUE TITLE
Issue with temperatures not varying

### ISSUE THREAD

**Issue by pjayathissa** [jamesdanielv/thermal_cam_mlx90640#1]
Hi, firstly thanks for preparing this UNO based source code

I am not sure whether I am following your methodology right. Would you be able to quickly document the step by step process when starting with a fresh melexis board? When I tried it I got relatively static temperatures that were around 27C +/- 1C.

**Comment by jamesdanielv** [comment]
hello, let me look into it and get back to you, i should reply before tue of next week if i find a solution for you.

have you tried the test runs first, one that serially scans the sensors and displays as dots on screen?

also there are settings that sometimes come changed as these devices are often tested before being shipped.

sometimes for example changing page refresh speed to at least 16 per second works. there should be commented code that should do this for you if settings are changed.

there also is the possibility that the code listed is not yet complete as i think it was to output to a thermal cam directly. unfortunately i've been distracted by a few other activities lately.  the goal is to eventually simplify the math further, and to make output directly to a display.

there are working code samples i have that should show how the cells work, and documentation provided with them as well at least on hackaday, i have also updated the github with documentation for the sensor.

I'm sorry your having issues, let me look into it this weekend and see what i can find for you.

james

________________________________

**Comment by pjayathissa** [comment]
Hey James

Thanks for the quick reply.

Maybe if you could let me know which zip file I should run, then that would already be a big help. Is it https://github.com/jamesdanielv/thermal_cam_mlx90640/blob/master/MLX906040_1tempcell.zip?

**Comment by jamesdanielv** [comment]
tempcell program only measures the temp of the silicon, the other sensor values it tests just output raw numbers. you should see around 24-28degrees for silicon sensor read. the idea is to calculate with offsets the sensor temp of silicon, and calc differences between the thermopiles. ill update the information on this more in the github, but i believe this is discussed in the notes on hackaday.


fullsensorreadToterminal.zip, is the example that you can test the entire sensor to display output with serial monitor.

also this code is a work in progress after this point. the code that i have to read the sensor data and convert it to temp is
32x24calibratedsensorRead.zip
________________________________

**Comment by jamesdanielv** [comment]
i have edited the readme with additional instructions to reference the hackaday article with work i've done on this sensor. i've also updates the readme to clearly state that the tempcell read program is for the read of the silicon temp only. the other sensor information is just analog values.  if you put your hand on silicon, or put near a warm object the ambient heat should change the temp value. 

if there are any other concerns with it, then please reopen this and let me know. thanks.
